out = open('job_vars.txt', 'w')
with open('job_names.txt') as f:
    f.readline()
    line = f.readline().split()
    out.write('BLACKSCHOLES_NAME="' + line[0] + '"\n')
    line = f.readline().split()
    out.write('CANNEAL_NAME="' + line[0] + '"\n')
    line = f.readline().split()
    out.write('DEDUP_NAME="' + line[0] + '"\n')
    line = f.readline().split()
    out.write('FERRET_NAME="' + line[0] + '"\n')
    line = f.readline().split()
    out.write('FREQMINE_NAME="' + line[0] + '"\n')
    line = f.readline().split()
    out.write('RADIX_NAME="' + line[0] + '"\n')
    line = f.readline().split()
    out.write('VIPS_NAME="' + line[0] + '"\n')
out.close()