out = open('node_vars.txt', 'w')
with open('nodes_data.txt') as f:
    f.readline()
    line = f.readline().split()
    out.write('AGENT_A_NAME="' + line[0] + '"\n')
    out.write('AGENT_A_INT_IP="' + line[5] + '"\n')
    line = f.readline().split()
    out.write('AGENT_B_NAME="' + line[0] + '"\n')
    out.write('AGENT_B_INT_IP="' + line[5] + '"\n')
    line = f.readline().split()
    out.write('MEASURE_NAME="' + line[0] + '"\n')
    out.write('MEASURE_INT_IP="' + line[5] + '"\n')
    f.readline()
    line = f.readline().split()
    out.write('NODE_A2_NAME="' + line[0] + '"\n')
    line = f.readline().split()
    out.write('NODE_B4_NAME="' + line[0] + '"\n')
    line = f.readline().split()
    out.write('NODE_C8_NAME="' + line[0] + '"\n')
out.close()